// NO VERTICAL         0b0000
#define MATES_SWIPE_NORTH    0b0001
#define MATES_SWIPE_SOUTH    0b0010
#define MATES_SWIPE_VERT     0b0011
// INVALID VERTICAL    0b0011
// NO HORIZONTAL       0b0000
#define MATES_SWIPE_EAST     0b0100
#define MATES_SWIPE_WEST     0b1000
#define MATES_SWIPE_HORZ     0b1100
// INVALID HORIZONTAL  0b1100

#define MATES_SWIPE_TLBR    (MATES_SWIPE_SOUTH | MATES_SWIPE_EAST)
#define MATES_SWIPE_TRBL    (MATES_SWIPE_SOUTH | MATES_SWIPE_WEST)
#define MATES_SWIPE_BLTR    (MATES_SWIPE_NORTH | MATES_SWIPE_EAST)
#define MATES_SWIPE_BRTL    (MATES_SWIPE_NORTH | MATES_SWIPE_WEST)